version: "3"

services:
  web:
    build: ./vote
    command: python app.py
    volumes:
     - .:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - "db-data:/var/lib/mysqldata/data"
    networks:
      - back-tier
  
  redis:
    image: redis:alpine
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
